// GENERATED by tool/coverage.sh — DO NOT EDIT BY HAND.
//
// Imports every non-generated library under lib/ so that files no test
// exercises still land in the coverage DENOMINATOR. Without this,
// `flutter test --coverage` silently omits untested files and the
// coverage number lies upward. Regenerate by re-running
// tool/coverage.sh whenever a file is added to or removed from lib/.
//
// ignore_for_file: unused_import
import 'package:offline_aac/data/board_export.dart';
import 'package:offline_aac/data/board_import.dart';
import 'package:offline_aac/data/board_repository.dart';
import 'package:offline_aac/data/database/app_database.dart';
import 'package:offline_aac/data/database/app_database.steps.dart';
import 'package:offline_aac/data/database/backup.dart';
import 'package:offline_aac/data/database/connection.dart';
import 'package:offline_aac/data/database/schema_versions.dart';
import 'package:offline_aac/data/database/tables.dart';
import 'package:offline_aac/data/media_store.dart';
import 'package:offline_aac/data/portable_board.dart';
import 'package:offline_aac/data/seed/starter_phrases.dart';
import 'package:offline_aac/data/settings_repository.dart';
import 'package:offline_aac/data/speech/audio_session_config.dart';
import 'package:offline_aac/data/speech/flutter_tts_speech_service.dart';
import 'package:offline_aac/data/speech/speech_service.dart';
import 'package:offline_aac/data/speech/voice_filter.dart';
import 'package:offline_aac/diagnostics/crash_log.dart';
import 'package:offline_aac/main.dart';
import 'package:offline_aac/model/aac_palette.dart';
import 'package:offline_aac/model/board_grid.dart';
import 'package:offline_aac/model/speak_outcome.dart';
import 'package:offline_aac/model/stock.dart';
import 'package:offline_aac/native/personal_voice_channel.dart';
import 'package:offline_aac/native/quick_tile_bridge.dart';
import 'package:offline_aac/speech/speech_controller.dart';
import 'package:offline_aac/ui/app.dart';
import 'package:offline_aac/ui/board/board_controller.dart';
import 'package:offline_aac/ui/board/board_screen.dart';
import 'package:offline_aac/ui/board/compose_field.dart';
import 'package:offline_aac/ui/board/edit_mode_button.dart';
import 'package:offline_aac/ui/board/phrase_tile.dart';
import 'package:offline_aac/ui/board/responsive_grid.dart';
import 'package:offline_aac/ui/core/instant_route.dart';
import 'package:offline_aac/ui/core/tokens.dart';
import 'package:offline_aac/ui/edit/edit_screen.dart';
import 'package:offline_aac/ui/edit/tile_editor.dart';
import 'package:offline_aac/ui/settings/portability_controller.dart';
import 'package:offline_aac/ui/settings/portability_io.dart';
import 'package:offline_aac/ui/settings/settings_controller.dart';
import 'package:offline_aac/ui/settings/settings_controls.dart';
import 'package:offline_aac/ui/settings/settings_screen.dart';
import 'package:offline_aac/ui/settings/show_settings_section.dart';
import 'package:offline_aac/ui/settings/voice_picker.dart';
import 'package:offline_aac/ui/show_text/line_fitter.dart';
import 'package:offline_aac/ui/show_text/show_text_screen.dart';
import 'package:offline_aac/ui/strings.dart';

void main() {}
