#!/usr/bin/env bash
#
# tool/coverage.sh — honest line coverage for Reed.
#
# WHY THIS EXISTS
# ---------------
# `flutter test --coverage` OMITS every file that no test imports. An untested
# file then contributes zero lines to the DENOMINATOR instead of counting as
# 0%. One well-tested file plus twenty untested ones can report ~100%. The
# number lies UPWARD — the unsafe direction — in a project whose only two
# feedback loops are the analyzer and this suite.
#
# The fix: generate test/coverage_helper_test.dart, which imports every
# non-generated library under lib/. Importing a file is enough to land its
# lines in the coverage report (with 0 hits if nothing executes them), so
# untested files re-enter the denominator and the number stops flattering.
#
# Generated code is then stripped so it neither pads the numerator nor the
# denominator. The strip patterns MIRROR the analyzer.exclude block in
# analysis_options.yaml — keep the two in sync or the number stops meaning
# anything (generated code linted-out but coverage-in, or the reverse).
#
# There is deliberately NO percentage gate here and none in CI. Coverage is a
# local report the dev reads, not a build status. See test/README.md.
#
set -euo pipefail

# Resolve the repo root from this script's own location (tool/ sits at root),
# so the script works regardless of the caller's cwd.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

# Package name, read from pubspec so the import prefix never drifts.
PKG="$(awk 'NR < 60 && /^name:/ { print $2; exit }' pubspec.yaml)"
HELPER="test/coverage_helper_test.dart"
LCOV_FILE="coverage/lcov.info"

# ---------------------------------------------------------------------------
# 1. Generate the coverage helper: import every NON-GENERATED lib/ library.
#    Skipped (matching analysis_options.yaml's exclude block):
#      - *.g.dart                        (drift / json_serializable; part files)
#      - *.drift.dart                    (drift, modern suffix — none today)
#      - generated_plugin_registrant.dart
#    Plus any `part of` file, which cannot be imported on its own.
# ---------------------------------------------------------------------------
echo "==> Generating $HELPER (every non-generated lib/ library)"
imports="$(
  find lib -type f -name '*.dart' \
    ! -name '*.g.dart' \
    ! -name '*.drift.dart' \
    ! -name 'generated_plugin_registrant.dart' \
  | while IFS= read -r f; do
      if head -n 20 "$f" | grep -qE '^part of '; then
        continue
      fi
      printf "import 'package:%s/%s';\n" "$PKG" "${f#lib/}"
    done | LC_ALL=C sort
)"

{
  echo "// GENERATED by tool/coverage.sh — DO NOT EDIT BY HAND."
  echo "//"
  echo "// Imports every non-generated library under lib/ so that files no test"
  echo "// exercises still land in the coverage DENOMINATOR. Without this,"
  echo "// \`flutter test --coverage\` silently omits untested files and the"
  echo "// coverage number lies upward. Regenerate by re-running"
  echo "// tool/coverage.sh whenever a file is added to or removed from lib/."
  echo "//"
  echo "// ignore_for_file: unused_import"
  echo "$imports"
  echo
  echo "void main() {}"
} > "$HELPER"

# ---------------------------------------------------------------------------
# 2. Run the suite with coverage. Produces coverage/lcov.info.
# ---------------------------------------------------------------------------
echo "==> Running flutter test --coverage"
flutter test --coverage

# ---------------------------------------------------------------------------
# 3. Strip generated files from lcov.info.
#    Patterns MIRROR analysis_options.yaml's analyzer.exclude — keep in sync.
#    Prefer lcov (2.x on ubuntu-24.04 CI); fall back to awk where it is absent
#    (e.g. a stock macOS dev box, where lcov is not installed by default).
# ---------------------------------------------------------------------------
echo "==> Stripping generated files from $LCOV_FILE"
if command -v lcov >/dev/null 2>&1; then
  echo "    lcov found — using lcov --remove"
  # --ignore-errors unused: lcov 2.x FAILS the whole command when a --remove
  # pattern matches nothing (there are no *.drift.dart files today). Required.
  lcov --remove "$LCOV_FILE" \
    'lib/**/*.g.dart' \
    'lib/**/*.drift.dart' \
    'lib/**/generated_plugin_registrant.dart' \
    -o "$LCOV_FILE" \
    --ignore-errors unused
else
  echo "    lcov not found — using awk fallback"
  # Buffer each SF:...end_of_record record; drop it whole if its source path
  # is a generated file, otherwise emit it verbatim.
  awk '
    { buf = buf $0 ORS }
    /^SF:/ && ($0 ~ /\.g\.dart$/ || $0 ~ /\.drift\.dart$/ \
              || $0 ~ /generated_plugin_registrant\.dart$/) { skip = 1 }
    $0 == "end_of_record" {
      if (!skip) printf "%s", buf
      buf = ""; skip = 0
    }
  ' "$LCOV_FILE" > "$LCOV_FILE.tmp"
  mv "$LCOV_FILE.tmp" "$LCOV_FILE"
fi

# ---------------------------------------------------------------------------
# 4. Prove the strip worked. Both counts MUST be 0.
# ---------------------------------------------------------------------------
g_count="$(grep -c 'SF:.*\.g\.dart' "$LCOV_FILE" || true)"
d_count="$(grep -c 'SF:.*\.drift\.dart' "$LCOV_FILE" || true)"
sf_total="$(grep -c '^SF:' "$LCOV_FILE" || true)"
echo "==> Verification:"
echo "    generated .g.dart records:    $g_count (must be 0)"
echo "    generated .drift.dart records: $d_count (must be 0)"
echo "    lib/ files in denominator:     $sf_total"
if [ "$g_count" != "0" ] || [ "$d_count" != "0" ]; then
  echo "!!! generated files remain in $LCOV_FILE — strip failed." >&2
  exit 1
fi
echo "==> Coverage report: $LCOV_FILE"
