import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:offline_aac/model/board_grid.dart';

import '../support/harness.dart';
import '../support/tiles.dart';

/// The board must hold at every device and every text scale, bold or not,
/// without a single label overflowing — because a tile that overflows at speak
/// time is silence for exactly the users (large text, low vision) this app is
/// for. A RenderFlex overflow fails a widget test by default; nothing here
/// suppresses that, so a green run is a real guarantee.
///
/// This is the COARSE net — "no configuration the layout picks ever
/// flex-overflows"; `label_fit_test` is the fine one that proves the reflow
/// actually kept every word (a clipped `Text` reports nothing, ever). 1.3 and
/// 1.5 sit in the list because nonlinear device scaling makes the mid-range the
/// non-obvious part; 3.0 is Larger Accessibility Sizes territory.
/// `TextScaler.linear` over-approximates on purpose: Android 14+ scales large
/// text LESS than linear, so this stresses big labels harder than a device would.
///
/// One `testWidgets` per tuple, generated by a `for` loop AROUND the call — never
/// a loop inside one test, because overflow reports once per RenderObject and
/// scales 2..n would go silently unchecked.
///
/// Coverage:
///  - board, BOTH layouts (3x4 and the 6-tile 3x2): 2 x 3 devices x 5 scales x 2
///    bold = 60 tests. The 6-tile layout is the legitimate 200% resolution and
///    must never be the untested escape hatch.
///  - edit mode: 3 x 5 x 2 = 30. Overflow only reports if a widget PAINTS, so
///    edit mode has zero coverage under a board test — it is pumped separately.
///  - the type-to-speak field is the 13th cell of the board and paints in every
///    board test above, so it is covered there; show-text mode fits by
///    construction and is exercised in test/ui/show_text/.
void main() {
  const scales = <double>[1, 1.3, 1.5, 2, 3];

  final layouts = <String, BoardGrid Function()>{
    '3x4': fixtureGrid,
    '3x2': fixtureGrid6,
  };

  for (final entry in layouts.entries) {
    final layoutName = entry.key;
    final gridOf = entry.value;
    for (final device in Device.all) {
      for (final scale in scales) {
        for (final bold in <bool>[false, true]) {
          testWidgets(
            'board $layoutName: no overflow @ ${device.name} x$scale'
            '${bold ? ' bold' : ''}',
            (tester) async {
              tester.useDevice(device);
              await tester.pumpApp(
                grid: gridOf(),
                textScale: scale,
                boldText: bold,
              );
              // A sanity that the board actually rendered — the top-left slot is
              // always present. NOT find.byType on the tile (a geometry read
              // belongs to a keyed finder).
              expect(find.byKey(const ValueKey<String>('slot_0_0')), findsOne);
              expect(
                tester.takeException(),
                isNull,
                reason:
                    'a label overflowed on ${device.name} at ${scale}x'
                    '${bold ? ' bold' : ''} ($layoutName) — that is silence for '
                    'a large-text user',
              );
            },
          );
        }
      }
    }
  }

  // Edit mode paints its own controls (move / hide / remove / the empty-slot +),
  // none of which the board test above renders. Its own tuple loop.
  for (final device in Device.all) {
    for (final scale in scales) {
      for (final bold in <bool>[false, true]) {
        testWidgets(
          'edit mode: no overflow @ ${device.name} x$scale'
          '${bold ? ' bold' : ''}',
          (tester) async {
            tester.useDevice(device);
            await tester.pumpApp(
              editing: true,
              textScale: scale,
              boldText: bold,
            );
            expect(
              tester.takeException(),
              isNull,
              reason:
                  'an edit-mode control overflowed on ${device.name} at '
                  '${scale}x${bold ? ' bold' : ''}',
            );
          },
        );
      }
    }
  }
}
